schema_version = "1.0.0"

blender_version_min = "4.2.0"
id = "cyanic_toolbox"
version = "0.9.0"
# https://spdx.org/licenses/
license = [
    "SPDX:CC-BY-SA-2.0",
    "MIT",
]
maintainer = "DrCyanide"
name = "Cyanic Toolbox"
tagline = "Tools for creating face mesh from image and posing rigify humans"
type = "add-on"
website = "https://github.com/DrCyanide/cyanic_toolbox"

# https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html#manifest
# 
# platforms = [“windows-x64”, “windows-arm64”, “macos-x64”, “macos-arm64”, “linux-x64”] # I don't have the means to test these other versions. You'd need to download their wheels to make it work. See wheel_dl.py 
platforms = ["windows-x64", "linux-x64"]

wheels = [
        "./wheels/jax-0.9.1-py3-none-any.whl",
        "./wheels/pillow-12.1.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
        "./wheels/kiwisolver-1.5.0-cp311-cp311-win_amd64.whl",
        "./wheels/scikit_image-0.26.0-cp311-cp311-win_amd64.whl",
        "./wheels/numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "./wheels/opt_einsum-3.4.0-py3-none-any.whl",
        "./wheels/cycler-0.12.1-py3-none-any.whl",
        "./wheels/six-1.17.0-py2.py3-none-any.whl",
        "./wheels/packaging-26.0-py3-none-any.whl",
        "./wheels/sounddevice-0.5.5-py3-none-win_amd64.whl",
        "./wheels/opencv_contrib_python-4.13.0.92-cp311-abi3-win_amd64.whl",
        "./wheels/tifffile-2026.3.3-py3-none-any.whl",
        "./wheels/imageio-2.37.3-py3-none-any.whl",
        "./wheels/networkx-3.6.1-py3-none-any.whl",
        "./wheels/ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl",
        "./wheels/fonttools-4.62.0-cp311-cp311-win_amd64.whl",
        "./wheels/scipy-1.17.1-cp311-cp311-win_amd64.whl",
        "./wheels/scipy-1.16.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
        "./wheels/cffi-2.0.0-cp311-cp311-win_amd64.whl",
        "./wheels/protobuf-4.25.8-cp311-abi3-win_amd64.whl",
        "./wheels/matplotlib-3.10.8-cp311-cp311-win_amd64.whl",
        "./wheels/lazy_loader-0.5-py3-none-any.whl",
        "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
        "./wheels/numpy-2.2.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "./wheels/opencv_python-4.13.0.92-cp311-abi3-win_amd64.whl",
        "./wheels/contourpy-1.3.3-cp311-cp311-win_amd64.whl",
        "./wheels/jaxlib-0.9.1-cp311-cp311-win_amd64.whl",
        "./wheels/pillow-12.1.1-cp311-cp311-win_amd64.whl",
        "./wheels/pyparsing-3.3.2-py3-none-any.whl",
        "./wheels/flatbuffers-25.12.19-py2.py3-none-any.whl",
        "./wheels/absl_py-2.4.0-py3-none-any.whl",
        "./wheels/msvc_runtime-14.44.35112-cp311-cp311-win_amd64.whl",
        "./wheels/pycparser-3.0-py3-none-any.whl",
        "./wheels/scikit_image-0.25.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "./wheels/numpy-1.26.4-cp311-cp311-win_amd64.whl",
        "./wheels/attrs-25.4.0-py3-none-any.whl",
        "./wheels/numpy-2.4.3-cp311-cp311-win_amd64.whl",
        "./wheels/opencv_python-4.13.0.92-cp311-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
        "./wheels/mediapipe-0.10.14-cp311-cp311-win_amd64.whl",
]



[permissions]
files = "Save facemesh and texture to disk, import images"